#!/usr/bin/env ruby

#
# provision a VM using the puppet manifests and modules from
# apache/infrastructure-puppet into a local vagrant VM
#

require 'fileutils'
require 'yaml'
require 'erb'
require 'deep_merge'

hostname = ARGV[0] || 'whimsy-vm3'
playpens = ENV['PLAYPEN_HOME'] || "#{Dir.home}/playpens"

# find infrastructure-puppet
begin
  ip = File.realpath('infrastructure-puppet')
rescue Errno::ENOENT
  require 'whimsy/asf'
  ip = ASF::Git['infrastructure-puppet']
end

# ensure infrastructure-puppet is set up
Dir.chdir(ip) {system 'bundle install'} unless File.exist? "#{ip}/Gemfile.lock"
Dir.chdir(ip) {system 'bin/pull'} unless File.exist? "#{ip}/3rdParty"

# utility method to update a file
def update_file(filename, contents)
  FileUtils.mkdir_p File.dirname(filename) if filename.include? '/'

  unless File.exist?(filename) and File.read(filename) == contents
    File.write(filename, contents)
  end
end

# read config file
config = YAML.load_file(__FILE__ + '.yaml')
config['classes'].deep_merge! config[hostname]['classes'] if config[hostname]
osname = config.fetch('hostname', {}).fetch('box', 'ubuntu/trusty64')

# create directory
Dir.chdir playpens
FileUtils.mkdir_p hostname
Dir.chdir hostname

# create files
config['files'].each do |file, contents|
  contents = ERB.new(contents).result()
  update_file file, contents
end

# copy manifests/site.pp
update_file "manifests/site.pp", File.read("#{ip}/manifests/site.pp")

# filter hiera.yaml
hiera = YAML.load(File.read("#{ip}/hiera.yaml").gsub('%{asfcolo}', 'vagrant'))
hiera[:backends].delete 'eyaml'
hiera.delete(:eyaml)
hiera[:yaml][:datadir] = '/vagrant/data'
update_file "hiera.yaml", YAML.dump(hiera)

# copy colo
colo = YAML.load(File.read("#{ip}/data/colo/vagrant.yaml"))
update_file "data/colo/vagrant.yaml", YAML.dump(colo)

# read infrastructure-puppet
node = YAML.load_file("#{ip}/data/nodes/#{hostname}.apache.org.yaml")

# remove classes
node['classes'].delete_if do |name|
  config['classes']['remove'].include? name.split(':').first
end

# remove ssl vhosts
vhosts = node['vhosts_whimsy::vhosts::vhosts'] ||
         node['vhosts_asf::vhosts::vhosts']
if vhosts
  vhosts.keys.grep(/-(ssl|443)$/).each do |https|
    http = https.sub('-443', '-80').sub('-ssl', '')
    vhosts[http] = vhosts[https]
    vhosts[http]['port'] = 80
    vhosts[http]['ssl'] = false
    vhosts[http].delete('ssl_cert')
    vhosts[http].delete('ssl_key')
    vhosts[http].delete('ssl_chain')
    vhosts.delete(https)
  end
end

# output data node
update_file "data/nodes/#{hostname}.apache.org.yaml", YAML.dump(node)

osname.sub! 'trusty64', '1404'

# copy and filter os.yaml
os = YAML.load_file("#{ip}/data/#{osname}.yaml")
os.delete 'apache::log_formats' ##TODO
os['classes'].delete_if do |name|
  config['classes']['remove'].include? name.split(':').first
end
update_file "data/#{osname}.yaml", YAML.dump(os)

# copy and filter common.yaml
common = YAML.load_file("#{ip}/data/common.yaml")
common['classes'].delete_if do |name|
  config['classes']['remove'].include? name.split(':').first
end
update_file "data/common.yaml", YAML.dump(common)

# copy modules
system 'rsync', '-a', '--delete', "#{ip}/modules/", 'modules/'
system 'rsync', '-a', '--delete', "#{ip}/3rdParty/", '3rdParty/'

# tailor slapd.conf
if node['classes'] and node['classes'].include? 'ldapserver'
  conf = File.read('modules/ldapserver/templates/slapd.conf.erb')

  # set rootpw to 'password'
  conf.sub! '<%= rootpw %>', 'password'

  # disable TLS
  conf.sub! /^security/, '# security'
  conf.gsub! /^TLS/, '# TLS'

  # remove replication servers
  conf.sub!(/^syncrepl.*?\n\n/m) do |block|
    block.gsub(/^/, '# ')
  end

  # remove replication
  conf.sub! /^mirrormode/, '# mirrormode'
  conf.sub! /^overlay syncprov/, '# overlay syncprov'
  conf.sub!(/^moduleload.*/) do |line|
    "<%- if mod == 'syncprov' -%>\n# #{line}\n" +
    "<%- else -%>\n#{line}\n<%- end -%>"
  end

  File.write('modules/ldapserver/templates/slapd.conf.erb', conf)
end

# provision updates
if `vagrant status`.include? 'running'
  system 'vagrant provision'
else
  system 'vagrant up'
end
